# render.yaml (Cleaned up)

services:
  - type: web
    name: superset-dashboard
    env: docker
    docker:
      dockerfile: Dockerfile
    # envVars section has been removed as we are now using the UI
    plan: free