services:
  - type: web
    name: superset-dashboard
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: SUPERSET_SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        sync: false  # Security improvement: value set manually in dashboard
      - key: SUPERSET_CONFIG_PATH
        value: /app/superset_config.py